function(log_info _context _message)
    foreach(_arg ${ARGN})

    endforeach()
endfunction()

function( log _level _message)
    if (NOT DOXYGEN_LOG_LEVEL)
        set(DOXYGEN_LOG_LEVEL WARN)
    endif()
    set(_log_levels "DEBUG;INFO;WARN")

    list(FIND _log_levels ${_level} _ind)
    if (_ind EQUAL -1)
        set(_ind 2)
    endif()
    list(FIND _log_levels ${DOXYGEN_LOG_LEVEL} _ind2)
    if (_ind2 EQUAL -1)
        set(_ind2 1)
    endif()
    if (${_ind} GREATER_EQUAL ${_ind2})
        if (${_level} STREQUAL WARN AND DOXYGEN_PROMOTE_WARNINGS)
            message(WARNING "${_message}")
        else()
            message(STATUS "[${_level}] ${_message}")
        endif()
    endif ()
endfunction()
